-- =============================================================================
-- V35: Complete MITRE ATT&CK Framework — All Enterprise Techniques
-- =============================================================================
-- Adds ~250+ techniques covering all 14 tactics of the MITRE ATT&CK Enterprise matrix
-- Uses INSERT IGNORE to skip the 15 techniques already seeded in V8

-- ===================== RECONNAISSANCE (TA0043) =====================
INSERT IGNORE INTO mitre_techniques (id, name, tactic, description, url) VALUES
('T1595', 'Active Scanning', 'Reconnaissance', 'Adversaries may execute active reconnaissance scans to gather information that can be used during targeting.', 'https://attack.mitre.org/techniques/T1595'),
('T1595.001', 'Scanning IP Blocks', 'Reconnaissance', 'Adversaries may scan victim IP blocks to gather information for targeting.', 'https://attack.mitre.org/techniques/T1595/001'),
('T1595.002', 'Vulnerability Scanning', 'Reconnaissance', 'Adversaries may scan victims for vulnerabilities that can be used during targeting.', 'https://attack.mitre.org/techniques/T1595/002'),
('T1595.003', 'Wordlist Scanning', 'Reconnaissance', 'Adversaries may iteratively probe infrastructure using brute-forcing and crawling techniques.', 'https://attack.mitre.org/techniques/T1595/003'),
('T1592', 'Gather Victim Host Information', 'Reconnaissance', 'Adversaries may gather information about the victim host that can be used during targeting.', 'https://attack.mitre.org/techniques/T1592'),
('T1592.001', 'Hardware', 'Reconnaissance', 'Adversaries may gather information about the victim host hardware that can be used during targeting.', 'https://attack.mitre.org/techniques/T1592/001'),
('T1592.002', 'Software', 'Reconnaissance', 'Adversaries may gather information about the victim host software that can be used during targeting.', 'https://attack.mitre.org/techniques/T1592/002'),
('T1592.003', 'Firmware', 'Reconnaissance', 'Adversaries may gather information about the victim host firmware that can be used during targeting.', 'https://attack.mitre.org/techniques/T1592/003'),
('T1592.004', 'Client Configurations', 'Reconnaissance', 'Adversaries may gather information about the victim client configurations that can be used during targeting.', 'https://attack.mitre.org/techniques/T1592/004'),
('T1589', 'Gather Victim Identity Information', 'Reconnaissance', 'Adversaries may gather information about the victim identity that can be used during targeting.', 'https://attack.mitre.org/techniques/T1589'),
('T1589.001', 'Credentials', 'Reconnaissance', 'Adversaries may gather credentials that can be used during targeting.', 'https://attack.mitre.org/techniques/T1589/001'),
('T1589.002', 'Email Addresses', 'Reconnaissance', 'Adversaries may gather email addresses that can be used during targeting.', 'https://attack.mitre.org/techniques/T1589/002'),
('T1589.003', 'Employee Names', 'Reconnaissance', 'Adversaries may gather employee names that can be used during targeting.', 'https://attack.mitre.org/techniques/T1589/003'),
('T1590', 'Gather Victim Network Information', 'Reconnaissance', 'Adversaries may gather information about the victim network that can be used during targeting.', 'https://attack.mitre.org/techniques/T1590'),
('T1590.001', 'Domain Properties', 'Reconnaissance', 'Adversaries may gather information about the victim domain properties.', 'https://attack.mitre.org/techniques/T1590/001'),
('T1590.002', 'DNS', 'Reconnaissance', 'Adversaries may gather information about the victim DNS that can be used during targeting.', 'https://attack.mitre.org/techniques/T1590/002'),
('T1590.004', 'Network Topology', 'Reconnaissance', 'Adversaries may gather information about the victim network topology.', 'https://attack.mitre.org/techniques/T1590/004'),
('T1590.005', 'IP Addresses', 'Reconnaissance', 'Adversaries may gather the victim IP addresses that can be used during targeting.', 'https://attack.mitre.org/techniques/T1590/005'),
('T1590.006', 'Network Security Appliances', 'Reconnaissance', 'Adversaries may gather information about the victim network security appliances.', 'https://attack.mitre.org/techniques/T1590/006'),
('T1591', 'Gather Victim Org Information', 'Reconnaissance', 'Adversaries may gather information about the victim organization that can be used during targeting.', 'https://attack.mitre.org/techniques/T1591'),
('T1591.001', 'Determine Physical Locations', 'Reconnaissance', 'Adversaries may gather the victim physical locations that can be used during targeting.', 'https://attack.mitre.org/techniques/T1591/001'),
('T1591.002', 'Business Relationships', 'Reconnaissance', 'Adversaries may gather information about the victim business relationships.', 'https://attack.mitre.org/techniques/T1591/002'),
('T1591.004', 'Identify Roles', 'Reconnaissance', 'Adversaries may gather information about identities and roles within the victim organization.', 'https://attack.mitre.org/techniques/T1591/004'),
('T1598', 'Phishing for Information', 'Reconnaissance', 'Adversaries may send phishing messages to elicit sensitive information that can be used during targeting.', 'https://attack.mitre.org/techniques/T1598'),
('T1598.001', 'Spearphishing Service', 'Reconnaissance', 'Adversaries may send spearphishing messages via third-party services to elicit sensitive information.', 'https://attack.mitre.org/techniques/T1598/001'),
('T1598.002', 'Spearphishing Attachment', 'Reconnaissance', 'Adversaries may send spearphishing messages with a malicious attachment to elicit sensitive information.', 'https://attack.mitre.org/techniques/T1598/002'),
('T1598.003', 'Spearphishing Link', 'Reconnaissance', 'Adversaries may send spearphishing messages with a malicious link to elicit sensitive information.', 'https://attack.mitre.org/techniques/T1598/003'),
('T1597', 'Search Closed Sources', 'Reconnaissance', 'Adversaries may search and gather information about victims from closed sources.', 'https://attack.mitre.org/techniques/T1597'),
('T1596', 'Search Open Technical Databases', 'Reconnaissance', 'Adversaries may search freely available technical databases for information about victims.', 'https://attack.mitre.org/techniques/T1596'),
('T1596.001', 'DNS/Passive DNS', 'Reconnaissance', 'Adversaries may search DNS data for information about victims.', 'https://attack.mitre.org/techniques/T1596/001'),
('T1596.002', 'WHOIS', 'Reconnaissance', 'Adversaries may search public WHOIS data for information about victims.', 'https://attack.mitre.org/techniques/T1596/002'),
('T1596.005', 'Scan Databases', 'Reconnaissance', 'Adversaries may search within public scan databases for information about victims.', 'https://attack.mitre.org/techniques/T1596/005'),
('T1593', 'Search Open Websites/Domains', 'Reconnaissance', 'Adversaries may search freely available websites and/or domains for information about victims.', 'https://attack.mitre.org/techniques/T1593'),
('T1593.001', 'Social Media', 'Reconnaissance', 'Adversaries may search social media for information about victims.', 'https://attack.mitre.org/techniques/T1593/001'),
('T1593.002', 'Search Engines', 'Reconnaissance', 'Adversaries may use search engines to collect information about victims.', 'https://attack.mitre.org/techniques/T1593/002'),
('T1594', 'Search Victim-Owned Websites', 'Reconnaissance', 'Adversaries may search websites owned by the victim for information.', 'https://attack.mitre.org/techniques/T1594');

-- ===================== RESOURCE DEVELOPMENT (TA0042) =====================
INSERT IGNORE INTO mitre_techniques (id, name, tactic, description, url) VALUES
('T1583', 'Acquire Infrastructure', 'Resource Development', 'Adversaries may buy, lease, or rent infrastructure for use during targeting.', 'https://attack.mitre.org/techniques/T1583'),
('T1583.001', 'Domains', 'Resource Development', 'Adversaries may acquire domains that can be used during targeting.', 'https://attack.mitre.org/techniques/T1583/001'),
('T1583.003', 'Virtual Private Server', 'Resource Development', 'Adversaries may rent VPS that can be used during targeting.', 'https://attack.mitre.org/techniques/T1583/003'),
('T1583.004', 'Server', 'Resource Development', 'Adversaries may buy, lease, or rent physical servers that can be used during targeting.', 'https://attack.mitre.org/techniques/T1583/004'),
('T1583.006', 'Web Services', 'Resource Development', 'Adversaries may register for web services that can be used during targeting.', 'https://attack.mitre.org/techniques/T1583/006'),
('T1586', 'Compromise Accounts', 'Resource Development', 'Adversaries may compromise accounts with services that can be used during targeting.', 'https://attack.mitre.org/techniques/T1586'),
('T1586.001', 'Social Media Accounts', 'Resource Development', 'Adversaries may compromise social media accounts that can be used during targeting.', 'https://attack.mitre.org/techniques/T1586/001'),
('T1586.002', 'Email Accounts', 'Resource Development', 'Adversaries may compromise email accounts that can be used during targeting.', 'https://attack.mitre.org/techniques/T1586/002'),
('T1584', 'Compromise Infrastructure', 'Resource Development', 'Adversaries may compromise third-party infrastructure that can be used during targeting.', 'https://attack.mitre.org/techniques/T1584'),
('T1587', 'Develop Capabilities', 'Resource Development', 'Adversaries may build capabilities that can be used during targeting.', 'https://attack.mitre.org/techniques/T1587'),
('T1587.001', 'Malware', 'Resource Development', 'Adversaries may develop malware and malware components that can be used during targeting.', 'https://attack.mitre.org/techniques/T1587/001'),
('T1587.003', 'Digital Certificates', 'Resource Development', 'Adversaries may create self-signed SSL/TLS certificates that can be used during targeting.', 'https://attack.mitre.org/techniques/T1587/003'),
('T1587.004', 'Exploits', 'Resource Development', 'Adversaries may develop exploits that can be used during targeting.', 'https://attack.mitre.org/techniques/T1587/004'),
('T1585', 'Establish Accounts', 'Resource Development', 'Adversaries may create and cultivate accounts with services for use during targeting.', 'https://attack.mitre.org/techniques/T1585'),
('T1588', 'Obtain Capabilities', 'Resource Development', 'Adversaries may buy and/or steal capabilities for use during targeting.', 'https://attack.mitre.org/techniques/T1588'),
('T1588.001', 'Malware', 'Resource Development', 'Adversaries may buy, steal, or download malware for use during targeting.', 'https://attack.mitre.org/techniques/T1588/001'),
('T1588.002', 'Tool', 'Resource Development', 'Adversaries may buy, steal, or download tools for use during targeting.', 'https://attack.mitre.org/techniques/T1588/002'),
('T1588.005', 'Exploits', 'Resource Development', 'Adversaries may buy, steal, or download exploits for use during targeting.', 'https://attack.mitre.org/techniques/T1588/005'),
('T1588.006', 'Vulnerabilities', 'Resource Development', 'Adversaries may acquire information about vulnerabilities for use during targeting.', 'https://attack.mitre.org/techniques/T1588/006'),
('T1608', 'Stage Capabilities', 'Resource Development', 'Adversaries may upload, install, or otherwise set up capabilities for use during targeting.', 'https://attack.mitre.org/techniques/T1608'),
('T1608.001', 'Upload Malware', 'Resource Development', 'Adversaries may upload malware to third-party or adversary controlled infrastructure.', 'https://attack.mitre.org/techniques/T1608/001'),
('T1608.005', 'Link Target', 'Resource Development', 'Adversaries may put in place resources that are referenced by a link for use during targeting.', 'https://attack.mitre.org/techniques/T1608/005');

-- ===================== INITIAL ACCESS (TA0001) =====================
INSERT IGNORE INTO mitre_techniques (id, name, tactic, description, url) VALUES
('T1190', 'Exploit Public-Facing Application', 'Initial Access', 'Adversaries may attempt to exploit a weakness in an Internet-facing host or system to initially access a network.', 'https://attack.mitre.org/techniques/T1190'),
('T1189', 'Drive-by Compromise', 'Initial Access', 'Adversaries may gain access to a system through a user visiting a website over the normal course of browsing.', 'https://attack.mitre.org/techniques/T1189'),
('T1566', 'Phishing', 'Initial Access', 'Adversaries may send phishing messages to gain access to victim systems.', 'https://attack.mitre.org/techniques/T1566'),
('T1566.001', 'Spearphishing Attachment', 'Initial Access', 'Adversaries may send spearphishing emails with a malicious attachment.', 'https://attack.mitre.org/techniques/T1566/001'),
('T1566.002', 'Spearphishing Link', 'Initial Access', 'Adversaries may send spearphishing emails with a malicious link.', 'https://attack.mitre.org/techniques/T1566/002'),
('T1566.003', 'Spearphishing via Service', 'Initial Access', 'Adversaries may send spearphishing messages via third-party services.', 'https://attack.mitre.org/techniques/T1566/003'),
('T1566.004', 'Spearphishing Voice', 'Initial Access', 'Adversaries may use voice communications to manipulate a user into providing access.', 'https://attack.mitre.org/techniques/T1566/004'),
('T1078', 'Valid Accounts', 'Initial Access, Persistence, Privilege Escalation, Defense Evasion', 'Adversaries may obtain and abuse credentials of existing accounts.', 'https://attack.mitre.org/techniques/T1078'),
('T1078.001', 'Default Accounts', 'Initial Access, Persistence, Privilege Escalation, Defense Evasion', 'Adversaries may obtain and abuse credentials of a default account.', 'https://attack.mitre.org/techniques/T1078/001'),
('T1078.002', 'Domain Accounts', 'Initial Access, Persistence, Privilege Escalation, Defense Evasion', 'Adversaries may obtain and abuse credentials of a domain account.', 'https://attack.mitre.org/techniques/T1078/002'),
('T1078.003', 'Local Accounts', 'Initial Access, Persistence, Privilege Escalation, Defense Evasion', 'Adversaries may obtain and abuse credentials of a local account.', 'https://attack.mitre.org/techniques/T1078/003'),
('T1078.004', 'Cloud Accounts', 'Initial Access, Persistence, Privilege Escalation, Defense Evasion', 'Adversaries may obtain and abuse credentials of a cloud account.', 'https://attack.mitre.org/techniques/T1078/004'),
('T1133', 'External Remote Services', 'Initial Access, Persistence', 'Adversaries may leverage external-facing remote services to initially access a network.', 'https://attack.mitre.org/techniques/T1133'),
('T1200', 'Hardware Additions', 'Initial Access', 'Adversaries may introduce hardware into a system or network to gain access.', 'https://attack.mitre.org/techniques/T1200'),
('T1091', 'Replication Through Removable Media', 'Initial Access, Lateral Movement', 'Adversaries may move onto systems by copying malware to removable media.', 'https://attack.mitre.org/techniques/T1091'),
('T1195', 'Supply Chain Compromise', 'Initial Access', 'Adversaries may manipulate products or delivery mechanisms prior to receipt by a final consumer.', 'https://attack.mitre.org/techniques/T1195'),
('T1195.001', 'Compromise Software Dependencies', 'Initial Access', 'Adversaries may manipulate software dependencies and development tools.', 'https://attack.mitre.org/techniques/T1195/001'),
('T1195.002', 'Compromise Software Supply Chain', 'Initial Access', 'Adversaries may manipulate application software prior to receipt by a final consumer.', 'https://attack.mitre.org/techniques/T1195/002'),
('T1199', 'Trusted Relationship', 'Initial Access', 'Adversaries may breach or leverage organizations who have access to intended victims.', 'https://attack.mitre.org/techniques/T1199');

-- ===================== EXECUTION (TA0002) =====================
INSERT IGNORE INTO mitre_techniques (id, name, tactic, description, url) VALUES
('T1059', 'Command and Scripting Interpreter', 'Execution', 'Adversaries may abuse command and script interpreters to execute commands, scripts, or binaries.', 'https://attack.mitre.org/techniques/T1059'),
('T1059.001', 'PowerShell', 'Execution', 'Adversaries may abuse PowerShell commands and scripts for execution.', 'https://attack.mitre.org/techniques/T1059/001'),
('T1059.003', 'Windows Command Shell', 'Execution', 'Adversaries may abuse the Windows command shell for execution.', 'https://attack.mitre.org/techniques/T1059/003'),
('T1059.004', 'Unix Shell', 'Execution', 'Adversaries may abuse Unix shell commands and scripts for execution.', 'https://attack.mitre.org/techniques/T1059/004'),
('T1059.005', 'Visual Basic', 'Execution', 'Adversaries may abuse Visual Basic (VB) for execution.', 'https://attack.mitre.org/techniques/T1059/005'),
('T1059.006', 'Python', 'Execution', 'Adversaries may abuse Python commands and scripts for execution.', 'https://attack.mitre.org/techniques/T1059/006'),
('T1059.007', 'JavaScript', 'Execution', 'Adversaries may abuse various implementations of JavaScript for execution.', 'https://attack.mitre.org/techniques/T1059/007'),
('T1059.008', 'Network Device CLI', 'Execution', 'Adversaries may abuse scripting or built-in command line interpreters on network devices.', 'https://attack.mitre.org/techniques/T1059/008'),
('T1059.009', 'Cloud API', 'Execution', 'Adversaries may abuse cloud APIs to execute malicious commands.', 'https://attack.mitre.org/techniques/T1059/009'),
('T1053', 'Scheduled Task/Job', 'Execution, Persistence, Privilege Escalation', 'Adversaries may abuse task scheduling functionality.', 'https://attack.mitre.org/techniques/T1053'),
('T1053.002', 'At', 'Execution, Persistence, Privilege Escalation', 'Adversaries may abuse the at utility to perform task scheduling for execution.', 'https://attack.mitre.org/techniques/T1053/002'),
('T1053.003', 'Cron', 'Execution, Persistence, Privilege Escalation', 'Adversaries may abuse the cron utility to perform task scheduling for execution.', 'https://attack.mitre.org/techniques/T1053/003'),
('T1053.005', 'Scheduled Task', 'Execution, Persistence, Privilege Escalation', 'Adversaries may abuse the Windows Task Scheduler.', 'https://attack.mitre.org/techniques/T1053/005'),
('T1047', 'Windows Management Instrumentation', 'Execution', 'Adversaries may abuse WMI to execute malicious commands and payloads.', 'https://attack.mitre.org/techniques/T1047'),
('T1203', 'Exploitation for Client Execution', 'Execution', 'Adversaries may exploit software vulnerabilities in client applications to execute code.', 'https://attack.mitre.org/techniques/T1203'),
('T1559', 'Inter-Process Communication', 'Execution', 'Adversaries may abuse inter-process communication mechanisms for local code or command execution.', 'https://attack.mitre.org/techniques/T1559'),
('T1106', 'Native API', 'Execution', 'Adversaries may interact with the native OS application programming interface to execute behaviors.', 'https://attack.mitre.org/techniques/T1106'),
('T1053.007', 'Container Orchestration Job', 'Execution, Persistence, Privilege Escalation', 'Adversaries may abuse task scheduling in container orchestration.', 'https://attack.mitre.org/techniques/T1053/007'),
('T1129', 'Shared Modules', 'Execution', 'Adversaries may execute malicious payloads via loading shared modules.', 'https://attack.mitre.org/techniques/T1129'),
('T1569', 'System Services', 'Execution', 'Adversaries may abuse system services or daemons to execute commands or programs.', 'https://attack.mitre.org/techniques/T1569'),
('T1569.001', 'Launchctl', 'Execution', 'Adversaries may abuse launchctl to execute commands or programs.', 'https://attack.mitre.org/techniques/T1569/001'),
('T1569.002', 'Service Execution', 'Execution', 'Adversaries may abuse the Windows service control manager to execute malicious commands.', 'https://attack.mitre.org/techniques/T1569/002'),
('T1204', 'User Execution', 'Execution', 'Adversaries may rely upon specific actions by a user for execution.', 'https://attack.mitre.org/techniques/T1204'),
('T1204.001', 'Malicious Link', 'Execution', 'An adversary may rely upon a user clicking a malicious link for execution.', 'https://attack.mitre.org/techniques/T1204/001'),
('T1204.002', 'Malicious File', 'Execution', 'An adversary may rely upon a user opening a malicious file for execution.', 'https://attack.mitre.org/techniques/T1204/002'),
('T1204.003', 'Malicious Image', 'Execution', 'Adversaries may rely on a user running a malicious image for execution.', 'https://attack.mitre.org/techniques/T1204/003'),
('T1047.001', 'WMI Event Subscription', 'Execution', 'Adversaries may establish persistence and elevate privileges by executing malicious content triggered by WMI event subscriptions.', 'https://attack.mitre.org/techniques/T1047/001');

-- ===================== PERSISTENCE (TA0003) =====================
INSERT IGNORE INTO mitre_techniques (id, name, tactic, description, url) VALUES
('T1098', 'Account Manipulation', 'Persistence, Privilege Escalation', 'Adversaries may manipulate accounts to maintain and/or elevate access to victim systems.', 'https://attack.mitre.org/techniques/T1098'),
('T1098.001', 'Additional Cloud Credentials', 'Persistence, Privilege Escalation', 'Adversaries may add adversary-controlled credentials to a cloud account.', 'https://attack.mitre.org/techniques/T1098/001'),
('T1098.004', 'SSH Authorized Keys', 'Persistence, Privilege Escalation', 'Adversaries may modify the SSH authorized_keys file to maintain persistence.', 'https://attack.mitre.org/techniques/T1098/004'),
('T1547', 'Boot or Logon Autostart Execution', 'Persistence, Privilege Escalation', 'Adversaries may configure system settings to automatically execute a program during system boot or logon.', 'https://attack.mitre.org/techniques/T1547'),
('T1547.001', 'Registry Run Keys / Startup Folder', 'Persistence, Privilege Escalation', 'Adversaries may achieve persistence by adding a program to a startup folder or referencing it with a Registry run key.', 'https://attack.mitre.org/techniques/T1547/001'),
('T1547.004', 'Winlogon Helper DLL', 'Persistence, Privilege Escalation', 'Adversaries may abuse features of Winlogon to execute DLLs during logon.', 'https://attack.mitre.org/techniques/T1547/004'),
('T1547.009', 'Shortcut Modification', 'Persistence, Privilege Escalation', 'Adversaries may create or modify shortcuts to run a program during system boot or user login.', 'https://attack.mitre.org/techniques/T1547/009'),
('T1136', 'Create Account', 'Persistence', 'Adversaries may create an account to maintain access to victim systems.', 'https://attack.mitre.org/techniques/T1136'),
('T1136.001', 'Local Account', 'Persistence', 'Adversaries may create a local account to maintain access to victim systems.', 'https://attack.mitre.org/techniques/T1136/001'),
('T1136.002', 'Domain Account', 'Persistence', 'Adversaries may create a domain account to maintain access to victim systems.', 'https://attack.mitre.org/techniques/T1136/002'),
('T1136.003', 'Cloud Account', 'Persistence', 'Adversaries may create a cloud account to maintain access to victim systems.', 'https://attack.mitre.org/techniques/T1136/003'),
('T1543', 'Create or Modify System Process', 'Persistence, Privilege Escalation', 'Adversaries may create or modify system-level processes to repeatedly execute malicious payloads.', 'https://attack.mitre.org/techniques/T1543'),
('T1543.001', 'Launch Agent', 'Persistence, Privilege Escalation', 'Adversaries may create or modify launch agents to repeatedly execute malicious payloads.', 'https://attack.mitre.org/techniques/T1543/001'),
('T1543.002', 'Systemd Service', 'Persistence, Privilege Escalation', 'Adversaries may create or modify systemd services to repeatedly execute malicious payloads.', 'https://attack.mitre.org/techniques/T1543/002'),
('T1543.003', 'Windows Service', 'Persistence, Privilege Escalation', 'Adversaries may create or modify Windows services to repeatedly execute malicious payloads.', 'https://attack.mitre.org/techniques/T1543/003'),
('T1546', 'Event Triggered Execution', 'Persistence, Privilege Escalation', 'Adversaries may establish persistence using system mechanisms that trigger execution based on specific events.', 'https://attack.mitre.org/techniques/T1546'),
('T1546.001', 'Change Default File Association', 'Persistence, Privilege Escalation', 'Adversaries may establish persistence by executing malicious content triggered by a file type association.', 'https://attack.mitre.org/techniques/T1546/001'),
('T1546.003', 'Windows Management Instrumentation Event', 'Persistence, Privilege Escalation', 'Adversaries may establish persistence and elevate privileges by executing malicious content triggered by a WMI event subscription.', 'https://attack.mitre.org/techniques/T1546/003'),
('T1546.008', 'Accessibility Features', 'Persistence, Privilege Escalation', 'Adversaries may establish persistence by executing malicious content triggered by accessibility features.', 'https://attack.mitre.org/techniques/T1546/008'),
('T1546.015', 'Component Object Model Hijacking', 'Persistence, Privilege Escalation', 'Adversaries may establish persistence by executing malicious content triggered by hijacked references to COM objects.', 'https://attack.mitre.org/techniques/T1546/015'),
('T1574', 'Hijack Execution Flow', 'Persistence, Privilege Escalation, Defense Evasion', 'Adversaries may execute their own malicious payloads by hijacking the way operating systems run programs.', 'https://attack.mitre.org/techniques/T1574'),
('T1574.001', 'DLL Search Order Hijacking', 'Persistence, Privilege Escalation, Defense Evasion', 'Adversaries may execute their own malicious payloads by hijacking the search order used to load DLLs.', 'https://attack.mitre.org/techniques/T1574/001'),
('T1574.002', 'DLL Side-Loading', 'Persistence, Privilege Escalation, Defense Evasion', 'Adversaries may execute their own malicious payloads by side-loading DLLs.', 'https://attack.mitre.org/techniques/T1574/002'),
('T1574.011', 'Services Registry Permissions Weakness', 'Persistence, Privilege Escalation, Defense Evasion', 'Adversaries may execute their own malicious payloads by hijacking the Registry entries used by services.', 'https://attack.mitre.org/techniques/T1574/011'),
('T1556', 'Modify Authentication Process', 'Persistence, Credential Access, Defense Evasion', 'Adversaries may modify authentication mechanisms to access user credentials or enable otherwise unwarranted access.', 'https://attack.mitre.org/techniques/T1556'),
('T1556.001', 'Domain Controller Authentication', 'Persistence, Credential Access, Defense Evasion', 'Adversaries may patch the authentication process on a domain controller to bypass the typical authentication mechanisms.', 'https://attack.mitre.org/techniques/T1556/001'),
('T1137', 'Office Application Startup', 'Persistence', 'Adversaries may leverage Microsoft Office-based applications for persistence.', 'https://attack.mitre.org/techniques/T1137'),
('T1542', 'Pre-OS Boot', 'Persistence, Defense Evasion', 'Adversaries may abuse Pre-OS Boot mechanisms to establish persistence on a system.', 'https://attack.mitre.org/techniques/T1542'),
('T1542.003', 'Bootkit', 'Persistence, Defense Evasion', 'Adversaries may use bootkits to persist on systems.', 'https://attack.mitre.org/techniques/T1542/003'),
('T1505', 'Server Software Component', 'Persistence', 'Adversaries may abuse legitimate extensible development features of servers to establish persistent access.', 'https://attack.mitre.org/techniques/T1505'),
('T1505.003', 'Web Shell', 'Persistence', 'Adversaries may backdoor web servers with web shells to establish persistent access.', 'https://attack.mitre.org/techniques/T1505/003'),
('T1505.004', 'IIS Components', 'Persistence', 'Adversaries may install malicious components that run on IIS to establish persistence.', 'https://attack.mitre.org/techniques/T1505/004');

-- ===================== PRIVILEGE ESCALATION (TA0004) =====================
INSERT IGNORE INTO mitre_techniques (id, name, tactic, description, url) VALUES
('T1548', 'Abuse Elevation Control Mechanism', 'Privilege Escalation, Defense Evasion', 'Adversaries may circumvent mechanisms designed to control elevated privileges.', 'https://attack.mitre.org/techniques/T1548'),
('T1548.001', 'Setuid and Setgid', 'Privilege Escalation, Defense Evasion', 'Adversaries may perform shell escapes or exploit vulnerabilities in an application with the setsuid or setgid bits set.', 'https://attack.mitre.org/techniques/T1548/001'),
('T1548.002', 'Bypass User Account Control', 'Privilege Escalation, Defense Evasion', 'Adversaries may bypass UAC mechanisms to elevate process privileges on system.', 'https://attack.mitre.org/techniques/T1548/002'),
('T1548.003', 'Sudo and Sudo Caching', 'Privilege Escalation, Defense Evasion', 'Adversaries may perform sudo caching and/or use the sudoers file to elevate privileges.', 'https://attack.mitre.org/techniques/T1548/003'),
('T1134', 'Access Token Manipulation', 'Privilege Escalation, Defense Evasion', 'Adversaries may modify access tokens to operate under a different user or system security context.', 'https://attack.mitre.org/techniques/T1134'),
('T1134.001', 'Token Impersonation/Theft', 'Privilege Escalation, Defense Evasion', 'Adversaries may duplicate then impersonate another user token to escalate privileges.', 'https://attack.mitre.org/techniques/T1134/001'),
('T1068', 'Exploitation for Privilege Escalation', 'Privilege Escalation', 'Adversaries may exploit software vulnerabilities to elevate privileges.', 'https://attack.mitre.org/techniques/T1068'),
('T1484', 'Domain Policy Modification', 'Privilege Escalation, Defense Evasion', 'Adversaries may modify the configuration settings of a domain to evade defenses.', 'https://attack.mitre.org/techniques/T1484'),
('T1484.001', 'Group Policy Modification', 'Privilege Escalation, Defense Evasion', 'Adversaries may modify Group Policy Objects to subvert the intended discretionary access controls.', 'https://attack.mitre.org/techniques/T1484/001'),
('T1611', 'Escape to Host', 'Privilege Escalation', 'Adversaries may break out of a container to gain access to the underlying host.', 'https://attack.mitre.org/techniques/T1611'),
('T1055', 'Process Injection', 'Privilege Escalation, Defense Evasion', 'Adversaries may inject code into processes to evade process-based defenses as well as elevate privileges.', 'https://attack.mitre.org/techniques/T1055'),
('T1055.001', 'Dynamic-link Library Injection', 'Privilege Escalation, Defense Evasion', 'Adversaries may inject DLLs into processes to evade defenses and elevate privileges.', 'https://attack.mitre.org/techniques/T1055/001'),
('T1055.003', 'Thread Execution Hijacking', 'Privilege Escalation, Defense Evasion', 'Adversaries may inject malicious code into hijacked process threads to evade detection.', 'https://attack.mitre.org/techniques/T1055/003'),
('T1055.012', 'Process Hollowing', 'Privilege Escalation, Defense Evasion', 'Adversaries may inject malicious code into suspended and hollowed processes.', 'https://attack.mitre.org/techniques/T1055/012');

-- ===================== DEFENSE EVASION (TA0005) =====================
INSERT IGNORE INTO mitre_techniques (id, name, tactic, description, url) VALUES
('T1562', 'Impair Defenses', 'Defense Evasion', 'Adversaries may maliciously modify components of a victim environment to hinder or disable defensive mechanisms.', 'https://attack.mitre.org/techniques/T1562'),
('T1562.001', 'Disable or Modify Tools', 'Defense Evasion', 'Adversaries may modify and/or disable security tools to avoid possible detection.', 'https://attack.mitre.org/techniques/T1562/001'),
('T1562.002', 'Disable Windows Event Logging', 'Defense Evasion', 'Adversaries may disable Windows event logging to limit data for detection.', 'https://attack.mitre.org/techniques/T1562/002'),
('T1562.004', 'Disable or Modify System Firewall', 'Defense Evasion', 'Adversaries may disable or modify system firewalls to bypass controls limiting network usage.', 'https://attack.mitre.org/techniques/T1562/004'),
('T1562.006', 'Indicator Blocking', 'Defense Evasion', 'Adversary may attempt to block indicators or events from leaving the host machine.', 'https://attack.mitre.org/techniques/T1562/006'),
('T1070', 'Indicator Removal', 'Defense Evasion', 'Adversaries may delete or modify artifacts generated within systems to remove evidence.', 'https://attack.mitre.org/techniques/T1070'),
('T1070.001', 'Clear Windows Event Logs', 'Defense Evasion', 'Adversaries may clear Windows Event Logs to hide the activity of an intrusion.', 'https://attack.mitre.org/techniques/T1070/001'),
('T1070.002', 'Clear Linux or Mac System Logs', 'Defense Evasion', 'Adversaries may clear system logs to hide evidence of an intrusion.', 'https://attack.mitre.org/techniques/T1070/002'),
('T1070.003', 'Clear Command History', 'Defense Evasion', 'Adversaries may clear command history to conceal the commands they ran.', 'https://attack.mitre.org/techniques/T1070/003'),
('T1070.004', 'File Deletion', 'Defense Evasion', 'Adversaries may delete files left behind by actions of their intrusion activity.', 'https://attack.mitre.org/techniques/T1070/004'),
('T1070.006', 'Timestomp', 'Defense Evasion', 'Adversaries may modify file time attributes to hide new or changes to existing files.', 'https://attack.mitre.org/techniques/T1070/006'),
('T1027', 'Obfuscated Files or Information', 'Defense Evasion', 'Adversaries may attempt to make an executable or file difficult to discover or analyze.', 'https://attack.mitre.org/techniques/T1027'),
('T1027.001', 'Binary Padding', 'Defense Evasion', 'Adversaries may use binary padding to add junk data and change the on-disk representation.', 'https://attack.mitre.org/techniques/T1027/001'),
('T1027.002', 'Software Packing', 'Defense Evasion', 'Adversaries may perform software packing to conceal their code.', 'https://attack.mitre.org/techniques/T1027/002'),
('T1027.004', 'Compile After Delivery', 'Defense Evasion', 'Adversaries may attempt to make payloads difficult to discover by delivering files to victims as uncompiled code.', 'https://attack.mitre.org/techniques/T1027/004'),
('T1027.005', 'Indicator Removal from Tools', 'Defense Evasion', 'Adversaries may remove indicators from tools if they believe their malicious tool was detected.', 'https://attack.mitre.org/techniques/T1027/005'),
('T1027.010', 'Command Obfuscation', 'Defense Evasion', 'Adversaries may obfuscate content during command execution to impede detection.', 'https://attack.mitre.org/techniques/T1027/010'),
('T1036', 'Masquerading', 'Defense Evasion', 'Adversaries may attempt to manipulate features of their artifacts to make them appear legitimate.', 'https://attack.mitre.org/techniques/T1036'),
('T1036.001', 'Invalid Code Signature', 'Defense Evasion', 'Adversaries may attempt to mimic features of valid code signatures to increase the chance of deceiving.', 'https://attack.mitre.org/techniques/T1036/001'),
('T1036.003', 'Rename System Utilities', 'Defense Evasion', 'Adversaries may rename legitimate system utilities to try to evade security mechanisms.', 'https://attack.mitre.org/techniques/T1036/003'),
('T1036.005', 'Match Legitimate Name or Location', 'Defense Evasion', 'Adversaries may match or approximate the name or location of legitimate files when naming malicious files.', 'https://attack.mitre.org/techniques/T1036/005'),
('T1218', 'System Binary Proxy Execution', 'Defense Evasion', 'Adversaries may bypass process and/or signature-based defenses by proxying execution through trusted system binaries.', 'https://attack.mitre.org/techniques/T1218'),
('T1218.001', 'Compiled HTML File', 'Defense Evasion', 'Adversaries may abuse Compiled HTML files (.chm) to conceal malicious code.', 'https://attack.mitre.org/techniques/T1218/001'),
('T1218.003', 'CMSTP', 'Defense Evasion', 'Adversaries may abuse CMSTP to proxy execution of malicious code.', 'https://attack.mitre.org/techniques/T1218/003'),
('T1218.005', 'Mshta', 'Defense Evasion', 'Adversaries may abuse mshta.exe to proxy execution of malicious .hta files.', 'https://attack.mitre.org/techniques/T1218/005'),
('T1218.010', 'Regsvr32', 'Defense Evasion', 'Adversaries may abuse Regsvr32.exe to proxy execution of malicious code.', 'https://attack.mitre.org/techniques/T1218/010'),
('T1218.011', 'Rundll32', 'Defense Evasion', 'Adversaries may abuse rundll32.exe to proxy execution of malicious code.', 'https://attack.mitre.org/techniques/T1218/011'),
('T1140', 'Deobfuscate/Decode Files or Information', 'Defense Evasion', 'Adversaries may use obfuscated files or information to hide artifacts of an intrusion.', 'https://attack.mitre.org/techniques/T1140'),
('T1112', 'Modify Registry', 'Defense Evasion', 'Adversaries may interact with the Windows Registry to hide configuration information within Registry keys.', 'https://attack.mitre.org/techniques/T1112'),
('T1564', 'Hide Artifacts', 'Defense Evasion', 'Adversaries may attempt to hide artifacts associated with their behaviors.', 'https://attack.mitre.org/techniques/T1564'),
('T1564.001', 'Hidden Files and Directories', 'Defense Evasion', 'Adversaries may set files and directories to be hidden to evade detection mechanisms.', 'https://attack.mitre.org/techniques/T1564/001'),
('T1564.003', 'Hidden Window', 'Defense Evasion', 'Adversaries may use hidden windows to conceal malicious activity.', 'https://attack.mitre.org/techniques/T1564/003'),
('T1497', 'Virtualization/Sandbox Evasion', 'Defense Evasion, Discovery', 'Adversaries may employ means to detect and avoid virtualization and analysis environments.', 'https://attack.mitre.org/techniques/T1497'),
('T1497.001', 'System Checks', 'Defense Evasion, Discovery', 'Adversaries may employ various system checks to detect and avoid virtualization.', 'https://attack.mitre.org/techniques/T1497/001'),
('T1620', 'Reflective Code Loading', 'Defense Evasion', 'Adversaries may reflectively load code into a process to conceal the execution of malicious payloads.', 'https://attack.mitre.org/techniques/T1620'),
('T1207', 'Rogue Domain Controller', 'Defense Evasion', 'Adversaries may register a rogue Domain Controller to enable manipulation of Active Directory data.', 'https://attack.mitre.org/techniques/T1207'),
('T1014', 'Rootkit', 'Defense Evasion', 'Adversaries may use rootkits to hide the presence of programs, files, network connections, services, etc.', 'https://attack.mitre.org/techniques/T1014'),
('T1553', 'Subvert Trust Controls', 'Defense Evasion', 'Adversaries may undermine security controls that will either warn users or prevent them from acting on potential threats.', 'https://attack.mitre.org/techniques/T1553'),
('T1553.002', 'Code Signing', 'Defense Evasion', 'Adversaries may create, acquire, or steal code signing materials to sign their malware or tools.', 'https://attack.mitre.org/techniques/T1553/002'),
('T1221', 'Template Injection', 'Defense Evasion', 'Adversaries may create or modify references in user document templates to conceal malicious code.', 'https://attack.mitre.org/techniques/T1221'),
('T1127', 'Trusted Developer Utilities Proxy Execution', 'Defense Evasion', 'Adversaries may take advantage of trusted developer utilities to proxy execution of malicious payloads.', 'https://attack.mitre.org/techniques/T1127'),
('T1535', 'Unused/Unsupported Cloud Regions', 'Defense Evasion', 'Adversaries may create cloud instances in unused geographic service regions to evade detection.', 'https://attack.mitre.org/techniques/T1535'),
('T1550', 'Use Alternate Authentication Material', 'Defense Evasion, Lateral Movement', 'Adversaries may use alternate authentication material to move laterally and bypass normal access controls.', 'https://attack.mitre.org/techniques/T1550'),
('T1550.001', 'Application Access Token', 'Defense Evasion, Lateral Movement', 'Adversaries may use stolen application access tokens to bypass authentication.', 'https://attack.mitre.org/techniques/T1550/001'),
('T1550.002', 'Pass the Hash', 'Defense Evasion, Lateral Movement', 'Adversaries may pass the hash using stolen password hashes to move laterally.', 'https://attack.mitre.org/techniques/T1550/002'),
('T1550.003', 'Pass the Ticket', 'Defense Evasion, Lateral Movement', 'Adversaries may pass the ticket using stolen Kerberos tickets to move laterally.', 'https://attack.mitre.org/techniques/T1550/003'),
('T1550.004', 'Web Session Cookie', 'Defense Evasion, Lateral Movement', 'Adversaries may use stolen web session cookies to gain access to web applications.', 'https://attack.mitre.org/techniques/T1550/004');

-- ===================== CREDENTIAL ACCESS (TA0006) =====================
INSERT IGNORE INTO mitre_techniques (id, name, tactic, description, url) VALUES
('T1110', 'Brute Force', 'Credential Access', 'Adversaries may use brute force techniques to gain access to accounts.', 'https://attack.mitre.org/techniques/T1110'),
('T1110.001', 'Password Guessing', 'Credential Access', 'Adversaries may guess passwords to attempt access to accounts.', 'https://attack.mitre.org/techniques/T1110/001'),
('T1110.002', 'Password Cracking', 'Credential Access', 'Adversaries may use password cracking to attempt to recover usable credentials.', 'https://attack.mitre.org/techniques/T1110/002'),
('T1110.003', 'Password Spraying', 'Credential Access', 'Adversaries may use a single or small list of commonly used passwords against many different accounts.', 'https://attack.mitre.org/techniques/T1110/003'),
('T1110.004', 'Credential Stuffing', 'Credential Access', 'Adversaries may use credentials obtained from breach dumps to gain access to accounts.', 'https://attack.mitre.org/techniques/T1110/004'),
('T1555', 'Credentials from Password Stores', 'Credential Access', 'Adversaries may search for common password storage locations to obtain user credentials.', 'https://attack.mitre.org/techniques/T1555'),
('T1555.001', 'Keychain', 'Credential Access', 'Adversaries may acquire credentials from Keychain.', 'https://attack.mitre.org/techniques/T1555/001'),
('T1555.003', 'Credentials from Web Browsers', 'Credential Access', 'Adversaries may acquire credentials from web browsers by reading files specific to the target browser.', 'https://attack.mitre.org/techniques/T1555/003'),
('T1212', 'Exploitation for Credential Access', 'Credential Access', 'Adversaries may exploit software vulnerabilities to collect credentials.', 'https://attack.mitre.org/techniques/T1212'),
('T1187', 'Forced Authentication', 'Credential Access', 'Adversaries may gather credential material by invoking or forcing a user to automatically provide authentication information.', 'https://attack.mitre.org/techniques/T1187'),
('T1056', 'Input Capture', 'Credential Access, Collection', 'Adversaries may use methods of capturing user input to obtain credentials or collect information.', 'https://attack.mitre.org/techniques/T1056'),
('T1056.001', 'Keylogging', 'Credential Access, Collection', 'Adversaries may log user keystrokes to intercept credentials.', 'https://attack.mitre.org/techniques/T1056/001'),
('T1557', 'Adversary-in-the-Middle', 'Credential Access, Collection', 'Adversaries may attempt to position themselves between two or more networked devices.', 'https://attack.mitre.org/techniques/T1557'),
('T1557.001', 'LLMNR/NBT-NS Poisoning and SMB Relay', 'Credential Access, Collection', 'Adversaries may spoof an authoritative source for name resolution to force communication.', 'https://attack.mitre.org/techniques/T1557/001'),
('T1557.002', 'ARP Cache Poisoning', 'Credential Access, Collection', 'Adversaries may poison ARP caches to position themselves between communicating hosts.', 'https://attack.mitre.org/techniques/T1557/002'),
('T1003', 'OS Credential Dumping', 'Credential Access', 'Adversaries may attempt to dump credentials to obtain account login and credential material.', 'https://attack.mitre.org/techniques/T1003'),
('T1003.001', 'LSASS Memory', 'Credential Access', 'Adversaries may attempt to access credential material stored in the process memory of LSASS.', 'https://attack.mitre.org/techniques/T1003/001'),
('T1003.002', 'Security Account Manager', 'Credential Access', 'Adversaries may attempt to extract credential material from the SAM database.', 'https://attack.mitre.org/techniques/T1003/002'),
('T1003.003', 'NTDS', 'Credential Access', 'Adversaries may attempt to access or create a copy of the Active Directory domain database.', 'https://attack.mitre.org/techniques/T1003/003'),
('T1003.006', 'DCSync', 'Credential Access', 'Adversaries may attempt to access credentials and other sensitive information by abusing a Windows DC replication.', 'https://attack.mitre.org/techniques/T1003/006'),
('T1003.008', '/etc/passwd and /etc/shadow', 'Credential Access', 'Adversaries may attempt to dump the contents of /etc/passwd and /etc/shadow.', 'https://attack.mitre.org/techniques/T1003/008'),
('T1528', 'Steal Application Access Token', 'Credential Access', 'Adversaries can steal application access tokens as a means of acquiring credentials.', 'https://attack.mitre.org/techniques/T1528'),
('T1558', 'Steal or Forge Kerberos Tickets', 'Credential Access', 'Adversaries may attempt to subvert Kerberos authentication by stealing or forging Kerberos tickets.', 'https://attack.mitre.org/techniques/T1558'),
('T1558.001', 'Golden Ticket', 'Credential Access', 'Adversaries who have the KRBTGT account password hash may forge Kerberos TGTs.', 'https://attack.mitre.org/techniques/T1558/001'),
('T1558.003', 'Kerberoasting', 'Credential Access', 'Adversaries may abuse a valid Kerberos ticket-granting ticket or sniff network traffic to obtain a ticket-granting service ticket.', 'https://attack.mitre.org/techniques/T1558/003'),
('T1539', 'Steal Web Session Cookie', 'Credential Access', 'Adversaries may steal web application or service session cookies.', 'https://attack.mitre.org/techniques/T1539'),
('T1552', 'Unsecured Credentials', 'Credential Access', 'Adversaries may search compromised systems to find and obtain insecurely stored credentials.', 'https://attack.mitre.org/techniques/T1552'),
('T1552.001', 'Credentials In Files', 'Credential Access', 'Adversaries may search local file systems and remote file shares for files containing insecurely stored credentials.', 'https://attack.mitre.org/techniques/T1552/001'),
('T1552.004', 'Private Keys', 'Credential Access', 'Adversaries may search for private key certificate files on compromised systems.', 'https://attack.mitre.org/techniques/T1552/004'),
('T1552.006', 'Group Policy Preferences', 'Credential Access', 'Adversaries may attempt to find unsecured credentials in Group Policy Preferences.', 'https://attack.mitre.org/techniques/T1552/006');

-- ===================== DISCOVERY (TA0007) =====================
INSERT IGNORE INTO mitre_techniques (id, name, tactic, description, url) VALUES
('T1046', 'Network Service Discovery', 'Discovery', 'Adversaries may attempt to get a listing of services running on remote hosts.', 'https://attack.mitre.org/techniques/T1046'),
('T1087', 'Account Discovery', 'Discovery', 'Adversaries may attempt to get a listing of valid accounts on a system or within an environment.', 'https://attack.mitre.org/techniques/T1087'),
('T1087.001', 'Local Account', 'Discovery', 'Adversaries may attempt to get a listing of local system accounts.', 'https://attack.mitre.org/techniques/T1087/001'),
('T1087.002', 'Domain Account', 'Discovery', 'Adversaries may attempt to get a listing of domain accounts.', 'https://attack.mitre.org/techniques/T1087/002'),
('T1087.003', 'Email Account', 'Discovery', 'Adversaries may attempt to get a listing of email addresses and accounts.', 'https://attack.mitre.org/techniques/T1087/003'),
('T1087.004', 'Cloud Account', 'Discovery', 'Adversaries may attempt to get a listing of cloud accounts.', 'https://attack.mitre.org/techniques/T1087/004'),
('T1010', 'Application Window Discovery', 'Discovery', 'Adversaries may attempt to get a listing of opened application windows.', 'https://attack.mitre.org/techniques/T1010'),
('T1217', 'Browser Information Discovery', 'Discovery', 'Adversaries may enumerate information about browsers to learn more about compromised environments.', 'https://attack.mitre.org/techniques/T1217'),
('T1580', 'Cloud Infrastructure Discovery', 'Discovery', 'Adversaries may attempt to discover cloud infrastructure.', 'https://attack.mitre.org/techniques/T1580'),
('T1538', 'Cloud Service Dashboard', 'Discovery', 'Adversaries may use a cloud service dashboard GUI to discover information about the cloud environment.', 'https://attack.mitre.org/techniques/T1538'),
('T1526', 'Cloud Service Discovery', 'Discovery', 'Adversaries may attempt to enumerate the cloud services running on a system after gaining access.', 'https://attack.mitre.org/techniques/T1526'),
('T1482', 'Domain Trust Discovery', 'Discovery', 'Adversaries may attempt to gather information on domain trust relationships.', 'https://attack.mitre.org/techniques/T1482'),
('T1083', 'File and Directory Discovery', 'Discovery', 'Adversaries may enumerate files and directories.', 'https://attack.mitre.org/techniques/T1083'),
('T1615', 'Group Policy Discovery', 'Discovery', 'Adversaries may gather information on Group Policy settings.', 'https://attack.mitre.org/techniques/T1615'),
('T1046.001', 'Network Service Scanning', 'Discovery', 'Adversaries may scan for services on network hosts.', 'https://attack.mitre.org/techniques/T1046/001'),
('T1135', 'Network Share Discovery', 'Discovery', 'Adversaries may look for folders and drives shared on remote systems.', 'https://attack.mitre.org/techniques/T1135'),
('T1040', 'Network Sniffing', 'Discovery, Credential Access', 'Adversaries may sniff network traffic to capture information about an environment.', 'https://attack.mitre.org/techniques/T1040'),
('T1201', 'Password Policy Discovery', 'Discovery', 'Adversaries may attempt to access detailed information about the password policy.', 'https://attack.mitre.org/techniques/T1201'),
('T1120', 'Peripheral Device Discovery', 'Discovery', 'Adversaries may attempt to gather information about attached peripheral devices.', 'https://attack.mitre.org/techniques/T1120'),
('T1069', 'Permission Groups Discovery', 'Discovery', 'Adversaries may attempt to discover group and permission settings.', 'https://attack.mitre.org/techniques/T1069'),
('T1057', 'Process Discovery', 'Discovery', 'Adversaries may attempt to get information about running processes.', 'https://attack.mitre.org/techniques/T1057'),
('T1012', 'Query Registry', 'Discovery', 'Adversaries may interact with the Windows Registry to gather information about the system.', 'https://attack.mitre.org/techniques/T1012'),
('T1018', 'Remote System Discovery', 'Discovery', 'Adversaries may attempt to get a listing of other systems by IP address, hostname, or identifiable detail.', 'https://attack.mitre.org/techniques/T1018'),
('T1518', 'Software Discovery', 'Discovery', 'Adversaries may attempt to get a listing of software and software versions.', 'https://attack.mitre.org/techniques/T1518'),
('T1518.001', 'Security Software Discovery', 'Discovery', 'Adversaries may attempt to get a listing of security software, configurations, defenses.', 'https://attack.mitre.org/techniques/T1518/001'),
('T1082', 'System Information Discovery', 'Discovery', 'Adversaries may attempt to get detailed information about the operating system and hardware.', 'https://attack.mitre.org/techniques/T1082'),
('T1016', 'System Network Configuration Discovery', 'Discovery', 'Adversaries may look for details about the network configuration and settings.', 'https://attack.mitre.org/techniques/T1016'),
('T1049', 'System Network Connections Discovery', 'Discovery', 'Adversaries may attempt to get a listing of network connections to or from the compromised system.', 'https://attack.mitre.org/techniques/T1049'),
('T1033', 'System Owner/User Discovery', 'Discovery', 'Adversaries may attempt to identify the primary user currently logged in or remote system owner.', 'https://attack.mitre.org/techniques/T1033'),
('T1007', 'System Service Discovery', 'Discovery', 'Adversaries may try to gather information about registered local system services.', 'https://attack.mitre.org/techniques/T1007');

-- ===================== LATERAL MOVEMENT (TA0008) =====================
INSERT IGNORE INTO mitre_techniques (id, name, tactic, description, url) VALUES
('T1021', 'Remote Services', 'Lateral Movement', 'Adversaries may use Valid Accounts to log into a service that accepts remote connections.', 'https://attack.mitre.org/techniques/T1021'),
('T1021.001', 'Remote Desktop Protocol', 'Lateral Movement', 'Adversaries may use Valid Accounts to log into a computer using RDP.', 'https://attack.mitre.org/techniques/T1021/001'),
('T1021.002', 'SMB/Windows Admin Shares', 'Lateral Movement', 'Adversaries may use Valid Accounts to interact with a remote network share using SMB.', 'https://attack.mitre.org/techniques/T1021/002'),
('T1021.003', 'Distributed Component Object Model', 'Lateral Movement', 'Adversaries may use Valid Accounts to interact with remote machines by taking advantage of DCOM.', 'https://attack.mitre.org/techniques/T1021/003'),
('T1021.004', 'SSH', 'Lateral Movement', 'Adversaries may use Valid Accounts to log into remote machines using SSH.', 'https://attack.mitre.org/techniques/T1021/004'),
('T1021.005', 'VNC', 'Lateral Movement', 'Adversaries may use Valid Accounts to remotely control machines using VNC.', 'https://attack.mitre.org/techniques/T1021/005'),
('T1021.006', 'Windows Remote Management', 'Lateral Movement', 'Adversaries may use Valid Accounts to interact with remote systems using WinRM.', 'https://attack.mitre.org/techniques/T1021/006'),
('T1210', 'Exploitation of Remote Services', 'Lateral Movement', 'Adversaries may exploit remote services to gain unauthorized access to internal systems.', 'https://attack.mitre.org/techniques/T1210'),
('T1534', 'Internal Spearphishing', 'Lateral Movement', 'Adversaries may use internal spearphishing to gain access to additional information or exploit systems.', 'https://attack.mitre.org/techniques/T1534'),
('T1570', 'Lateral Tool Transfer', 'Lateral Movement', 'Adversaries may transfer tools or other files between systems in a compromised environment.', 'https://attack.mitre.org/techniques/T1570'),
('T1563', 'Remote Service Session Hijacking', 'Lateral Movement', 'Adversaries may take control of preexisting sessions with remote services to move laterally.', 'https://attack.mitre.org/techniques/T1563'),
('T1563.001', 'SSH Hijacking', 'Lateral Movement', 'Adversaries may hijack a legitimate user SSH session to move laterally.', 'https://attack.mitre.org/techniques/T1563/001'),
('T1563.002', 'RDP Hijacking', 'Lateral Movement', 'Adversaries may hijack a legitimate user RDP session to move laterally.', 'https://attack.mitre.org/techniques/T1563/002'),
('T1080', 'Taint Shared Content', 'Lateral Movement', 'Adversaries may deliver payloads to remote systems by adding content to shared storage locations.', 'https://attack.mitre.org/techniques/T1080');

-- ===================== COLLECTION (TA0009) =====================
INSERT IGNORE INTO mitre_techniques (id, name, tactic, description, url) VALUES
('T1560', 'Archive Collected Data', 'Collection', 'Adversaries may compress and/or encrypt data that is collected prior to exfiltration.', 'https://attack.mitre.org/techniques/T1560'),
('T1560.001', 'Archive via Utility', 'Collection', 'Adversaries may use utilities to compress and/or encrypt collected data prior to exfiltration.', 'https://attack.mitre.org/techniques/T1560/001'),
('T1123', 'Audio Capture', 'Collection', 'Adversaries may leverage a computers peripheral devices to capture audio recordings.', 'https://attack.mitre.org/techniques/T1123'),
('T1119', 'Automated Collection', 'Collection', 'Adversaries may use automated techniques for collecting internal data.', 'https://attack.mitre.org/techniques/T1119'),
('T1185', 'Browser Session Hijacking', 'Collection', 'Adversaries may take advantage of security vulnerabilities in browser-based processes to gain access to information.', 'https://attack.mitre.org/techniques/T1185'),
('T1115', 'Clipboard Data', 'Collection', 'Adversaries may collect data stored in the clipboard from users.', 'https://attack.mitre.org/techniques/T1115'),
('T1530', 'Data from Cloud Storage', 'Collection', 'Adversaries may access data from cloud storage.', 'https://attack.mitre.org/techniques/T1530'),
('T1213', 'Data from Information Repositories', 'Collection', 'Adversaries may leverage information repositories to mine valuable information.', 'https://attack.mitre.org/techniques/T1213'),
('T1213.001', 'Confluence', 'Collection', 'Adversaries may leverage Confluence repositories to mine valuable information.', 'https://attack.mitre.org/techniques/T1213/001'),
('T1213.002', 'Sharepoint', 'Collection', 'Adversaries may leverage Sharepoint repositories to mine valuable information.', 'https://attack.mitre.org/techniques/T1213/002'),
('T1005', 'Data from Local System', 'Collection', 'Adversaries may search local system sources, such as file systems and configuration files.', 'https://attack.mitre.org/techniques/T1005'),
('T1039', 'Data from Network Shared Drive', 'Collection', 'Adversaries may search network shares on computers they have compromised.', 'https://attack.mitre.org/techniques/T1039'),
('T1025', 'Data from Removable Media', 'Collection', 'Adversaries may search connected removable media on computers they have compromised.', 'https://attack.mitre.org/techniques/T1025'),
('T1074', 'Data Staged', 'Collection', 'Adversaries may stage collected data in a central location or directory prior to exfiltration.', 'https://attack.mitre.org/techniques/T1074'),
('T1074.001', 'Local Data Staging', 'Collection', 'Adversaries may stage collected data in a central location on the local system.', 'https://attack.mitre.org/techniques/T1074/001'),
('T1074.002', 'Remote Data Staging', 'Collection', 'Adversaries may stage collected data in a central location on a remote system.', 'https://attack.mitre.org/techniques/T1074/002'),
('T1114', 'Email Collection', 'Collection', 'Adversaries may target user email to collect sensitive information.', 'https://attack.mitre.org/techniques/T1114'),
('T1114.001', 'Local Email Collection', 'Collection', 'Adversaries may target user email on local systems to collect sensitive information.', 'https://attack.mitre.org/techniques/T1114/001'),
('T1114.002', 'Remote Email Collection', 'Collection', 'Adversaries may target an Exchange server to collect sensitive information.', 'https://attack.mitre.org/techniques/T1114/002'),
('T1114.003', 'Email Forwarding Rule', 'Collection', 'Adversaries may setup email forwarding rules to collect sensitive information.', 'https://attack.mitre.org/techniques/T1114/003'),
('T1113', 'Screen Capture', 'Collection', 'Adversaries may attempt to take screen captures of the desktop.', 'https://attack.mitre.org/techniques/T1113'),
('T1125', 'Video Capture', 'Collection', 'Adversaries may leverage a computers video devices to capture video recordings.', 'https://attack.mitre.org/techniques/T1125');

-- ===================== COMMAND AND CONTROL (TA0011) =====================
INSERT IGNORE INTO mitre_techniques (id, name, tactic, description, url) VALUES
('T1071', 'Application Layer Protocol', 'Command and Control', 'Adversaries may communicate using OSI application layer protocols.', 'https://attack.mitre.org/techniques/T1071'),
('T1071.001', 'Web Protocols', 'Command and Control', 'Adversaries may communicate using application layer protocols associated with web traffic.', 'https://attack.mitre.org/techniques/T1071/001'),
('T1071.002', 'File Transfer Protocols', 'Command and Control', 'Adversaries may communicate using FTP.', 'https://attack.mitre.org/techniques/T1071/002'),
('T1071.003', 'Mail Protocols', 'Command and Control', 'Adversaries may communicate using application layer protocols associated with email.', 'https://attack.mitre.org/techniques/T1071/003'),
('T1071.004', 'DNS', 'Command and Control', 'Adversaries may communicate using the DNS application layer protocol.', 'https://attack.mitre.org/techniques/T1071/004'),
('T1132', 'Data Encoding', 'Command and Control', 'Adversaries may encode data to make the content of command and control traffic more difficult to detect.', 'https://attack.mitre.org/techniques/T1132'),
('T1132.001', 'Standard Encoding', 'Command and Control', 'Adversaries may encode data with a standard data encoding system.', 'https://attack.mitre.org/techniques/T1132/001'),
('T1001', 'Data Obfuscation', 'Command and Control', 'Adversaries may obfuscate command and control traffic.', 'https://attack.mitre.org/techniques/T1001'),
('T1001.001', 'Junk Data', 'Command and Control', 'Adversaries may add junk data to protocols used for command and control.', 'https://attack.mitre.org/techniques/T1001/001'),
('T1001.002', 'Steganography', 'Command and Control', 'Adversaries may use steganographic techniques to hide command and control traffic.', 'https://attack.mitre.org/techniques/T1001/002'),
('T1568', 'Dynamic Resolution', 'Command and Control', 'Adversaries may dynamically establish connections to command and control infrastructure.', 'https://attack.mitre.org/techniques/T1568'),
('T1568.001', 'Fast Flux DNS', 'Command and Control', 'Adversaries may use Fast Flux DNS to hide a command and control channel.', 'https://attack.mitre.org/techniques/T1568/001'),
('T1568.002', 'Domain Generation Algorithms', 'Command and Control', 'Adversaries may make use of DGA to dynamically identify C2 destinations.', 'https://attack.mitre.org/techniques/T1568/002'),
('T1573', 'Encrypted Channel', 'Command and Control', 'Adversaries may employ a known encryption algorithm to conceal command and control traffic.', 'https://attack.mitre.org/techniques/T1573'),
('T1573.001', 'Symmetric Cryptography', 'Command and Control', 'Adversaries may employ symmetric encryption to conceal C2 traffic.', 'https://attack.mitre.org/techniques/T1573/001'),
('T1573.002', 'Asymmetric Cryptography', 'Command and Control', 'Adversaries may employ asymmetric encryption to conceal C2 traffic.', 'https://attack.mitre.org/techniques/T1573/002'),
('T1008', 'Fallback Channels', 'Command and Control', 'Adversaries may use fallback or alternate communication channels if the primary channel is compromised.', 'https://attack.mitre.org/techniques/T1008'),
('T1105', 'Ingress Tool Transfer', 'Command and Control', 'Adversaries may transfer tools or other files from an external system into a compromised environment.', 'https://attack.mitre.org/techniques/T1105'),
('T1104', 'Multi-Stage Channels', 'Command and Control', 'Adversaries may create multiple stages for C2 that are employed under different conditions.', 'https://attack.mitre.org/techniques/T1104'),
('T1095', 'Non-Application Layer Protocol', 'Command and Control', 'Adversaries may use an OSI non-application layer protocol for C2.', 'https://attack.mitre.org/techniques/T1095'),
('T1571', 'Non-Standard Port', 'Command and Control', 'Adversaries may communicate using a protocol and port pairing that are typically not associated.', 'https://attack.mitre.org/techniques/T1571'),
('T1572', 'Protocol Tunneling', 'Command and Control', 'Adversaries may tunnel network communications to and from a victim system within a separate protocol.', 'https://attack.mitre.org/techniques/T1572'),
('T1090', 'Proxy', 'Command and Control', 'Adversaries may use a connection proxy to direct network traffic between systems.', 'https://attack.mitre.org/techniques/T1090'),
('T1090.001', 'Internal Proxy', 'Command and Control', 'Adversaries may use an internal proxy to direct command and control traffic.', 'https://attack.mitre.org/techniques/T1090/001'),
('T1090.002', 'External Proxy', 'Command and Control', 'Adversaries may use an external proxy to act as an intermediary for C2 traffic.', 'https://attack.mitre.org/techniques/T1090/002'),
('T1090.003', 'Multi-hop Proxy', 'Command and Control', 'Adversaries may chain together multiple proxies to disguise the source of C2 traffic.', 'https://attack.mitre.org/techniques/T1090/003'),
('T1219', 'Remote Access Software', 'Command and Control', 'Adversaries may use legitimate desktop support and remote access software to establish an interactive C2 channel.', 'https://attack.mitre.org/techniques/T1219'),
('T1102', 'Web Service', 'Command and Control', 'Adversaries may use an existing, legitimate external Web service as a means for relaying C2 data.', 'https://attack.mitre.org/techniques/T1102'),
('T1102.001', 'Dead Drop Resolver', 'Command and Control', 'Adversaries may use an existing web service to host information for C2.', 'https://attack.mitre.org/techniques/T1102/001'),
('T1102.002', 'Bidirectional Communication', 'Command and Control', 'Adversaries may use an existing web service for bidirectional C2 communication.', 'https://attack.mitre.org/techniques/T1102/002');

-- ===================== EXFILTRATION (TA0010) =====================
INSERT IGNORE INTO mitre_techniques (id, name, tactic, description, url) VALUES
('T1020', 'Automated Exfiltration', 'Exfiltration', 'Adversaries may exfiltrate data using automated processing after being gathered during Collection.', 'https://attack.mitre.org/techniques/T1020'),
('T1030', 'Data Transfer Size Limits', 'Exfiltration', 'Adversaries may exfiltrate data in fixed size chunks instead of whole files.', 'https://attack.mitre.org/techniques/T1030'),
('T1048', 'Exfiltration Over Alternative Protocol', 'Exfiltration', 'Adversaries may steal data by exfiltrating it over a different protocol than the existing C2 channel.', 'https://attack.mitre.org/techniques/T1048'),
('T1048.001', 'Exfiltration Over Symmetric Encrypted Non-C2 Protocol', 'Exfiltration', 'Adversaries may steal data by exfiltrating it over a symmetrically encrypted non-C2 protocol.', 'https://attack.mitre.org/techniques/T1048/001'),
('T1048.002', 'Exfiltration Over Asymmetric Encrypted Non-C2 Protocol', 'Exfiltration', 'Adversaries may steal data by exfiltrating it over an asymmetrically encrypted non-C2 protocol.', 'https://attack.mitre.org/techniques/T1048/002'),
('T1048.003', 'Exfiltration Over Unencrypted Non-C2 Protocol', 'Exfiltration', 'Adversaries may steal data by exfiltrating it over an un-encrypted non-C2 protocol.', 'https://attack.mitre.org/techniques/T1048/003'),
('T1041', 'Exfiltration Over C2 Channel', 'Exfiltration', 'Adversaries may steal data by exfiltrating it over an existing command and control channel.', 'https://attack.mitre.org/techniques/T1041'),
('T1011', 'Exfiltration Over Other Network Medium', 'Exfiltration', 'Adversaries may attempt to exfiltrate data over a different network medium than the C2 channel.', 'https://attack.mitre.org/techniques/T1011'),
('T1052', 'Exfiltration Over Physical Medium', 'Exfiltration', 'Adversaries may attempt to exfiltrate data via a physical medium.', 'https://attack.mitre.org/techniques/T1052'),
('T1567', 'Exfiltration Over Web Service', 'Exfiltration', 'Adversaries may use an existing, legitimate external Web service to exfiltrate data.', 'https://attack.mitre.org/techniques/T1567'),
('T1567.001', 'Exfiltration to Code Repository', 'Exfiltration', 'Adversaries may exfiltrate data to a code repository.', 'https://attack.mitre.org/techniques/T1567/001'),
('T1567.002', 'Exfiltration to Cloud Storage', 'Exfiltration', 'Adversaries may exfiltrate data to a cloud storage service.', 'https://attack.mitre.org/techniques/T1567/002'),
('T1029', 'Scheduled Transfer', 'Exfiltration', 'Adversaries may schedule data exfiltration to be performed only at certain times of day or at certain intervals.', 'https://attack.mitre.org/techniques/T1029'),
('T1537', 'Transfer Data to Cloud Account', 'Exfiltration', 'Adversaries may exfiltrate data by transferring the data to another cloud account.', 'https://attack.mitre.org/techniques/T1537');

-- ===================== IMPACT (TA0040) =====================
INSERT IGNORE INTO mitre_techniques (id, name, tactic, description, url) VALUES
('T1531', 'Account Access Removal', 'Impact', 'Adversaries may interrupt availability of system and network resources by inhibiting access to accounts.', 'https://attack.mitre.org/techniques/T1531'),
('T1485', 'Data Destruction', 'Impact', 'Adversaries may destroy data and files on specific systems or in large numbers.', 'https://attack.mitre.org/techniques/T1485'),
('T1486', 'Data Encrypted for Impact', 'Impact', 'Adversaries may encrypt data on target systems to interrupt availability.', 'https://attack.mitre.org/techniques/T1486'),
('T1565', 'Data Manipulation', 'Impact', 'Adversaries may insert, delete, or manipulate data to influence external outcomes.', 'https://attack.mitre.org/techniques/T1565'),
('T1565.001', 'Stored Data Manipulation', 'Impact', 'Adversaries may insert, delete, or manipulate data at rest to influence external outcomes.', 'https://attack.mitre.org/techniques/T1565/001'),
('T1565.002', 'Transmitted Data Manipulation', 'Impact', 'Adversaries may alter data en route to storage or other systems to manipulate external outcomes.', 'https://attack.mitre.org/techniques/T1565/002'),
('T1491', 'Defacement', 'Impact', 'Adversaries may modify visual content available internally or externally to an enterprise network.', 'https://attack.mitre.org/techniques/T1491'),
('T1491.001', 'Internal Defacement', 'Impact', 'Adversaries may deface systems internal to an organization.', 'https://attack.mitre.org/techniques/T1491/001'),
('T1491.002', 'External Defacement', 'Impact', 'Adversaries may deface systems external to an organization.', 'https://attack.mitre.org/techniques/T1491/002'),
('T1561', 'Disk Wipe', 'Impact', 'Adversaries may wipe or corrupt raw disk data on specific systems or in large numbers.', 'https://attack.mitre.org/techniques/T1561'),
('T1561.001', 'Disk Content Wipe', 'Impact', 'Adversaries may erase the contents of storage devices on specific systems or in large numbers.', 'https://attack.mitre.org/techniques/T1561/001'),
('T1561.002', 'Disk Structure Wipe', 'Impact', 'Adversaries may corrupt or wipe the disk data structures on a hard drive necessary to boot a system.', 'https://attack.mitre.org/techniques/T1561/002'),
('T1499', 'Endpoint Denial of Service', 'Impact', 'Adversaries may perform Endpoint Denial of Service attacks to degrade or block the availability of services.', 'https://attack.mitre.org/techniques/T1499'),
('T1499.001', 'OS Exhaustion Flood', 'Impact', 'Adversaries may target the operating system to cause a denial of service.', 'https://attack.mitre.org/techniques/T1499/001'),
('T1499.002', 'Service Exhaustion Flood', 'Impact', 'Adversaries may target the different network services to cause a denial of service.', 'https://attack.mitre.org/techniques/T1499/002'),
('T1499.003', 'Application Exhaustion Flood', 'Impact', 'Adversaries may target resource-intensive features of applications to cause a denial of service.', 'https://attack.mitre.org/techniques/T1499/003'),
('T1499.004', 'Application or System Exploitation', 'Impact', 'Adversaries may exploit software vulnerabilities that can cause an application to crash or be taken down.', 'https://attack.mitre.org/techniques/T1499/004'),
('T1498', 'Network Denial of Service', 'Impact', 'Adversaries may perform NDoS attacks to degrade or block the availability of targeted resources.', 'https://attack.mitre.org/techniques/T1498'),
('T1498.001', 'Direct Network Flood', 'Impact', 'Adversaries may attempt to cause a DoS by directly sending a high-volume of network traffic.', 'https://attack.mitre.org/techniques/T1498/001'),
('T1498.002', 'Reflection Amplification', 'Impact', 'Adversaries may attempt to cause a DoS by reflecting a high-volume of network traffic to a target.', 'https://attack.mitre.org/techniques/T1498/002'),
('T1496', 'Resource Hijacking', 'Impact', 'Adversaries may leverage the resources of co-opted systems to complete resource-intensive tasks.', 'https://attack.mitre.org/techniques/T1496'),
('T1489', 'Service Stop', 'Impact', 'Adversaries may stop or disable services on a system to render those services unavailable.', 'https://attack.mitre.org/techniques/T1489'),
('T1529', 'System Shutdown/Reboot', 'Impact', 'Adversaries may shutdown/reboot systems to interrupt access to, or aid in the destruction of, those systems.', 'https://attack.mitre.org/techniques/T1529');
